Repository scm-manager/scm-jenkins-plugin, pull requests merged in 2020-07, with the labels that each got.

#7 allow variable build parameters
  CHANGELOG.md
  src/main/java/sonia/scm/jenkins/JenkinsHook.java
  src/main/java/sonia/scm/jenkins/JenkinsRepositoryHookHandler.java
  src/main/resources/locales/de/plugins.json
  src/main/resources/locales/en/plugins.json
  src/test/java/sonia/scm/jenkins/JenkinsRepositoryHookHandlerTest.java
Labels: enhancement

#6 improve documentation
  docs/en/configuration/assets/global-config.png
  docs/en/configuration/assets/repo-config.png
  docs/en/configuration/index.md
  docs/en/navigation.yml
  docs/en/permissions.md
Labels: documentation

#10 use the expression language parser from scm-el-plugin
  CHANGELOG.md
  pom.xml
  src/main/java/sonia/scm/jenkins/JenkinsHook.java
  src/main/java/sonia/scm/jenkins/JenkinsRepositoryHookHandler.java
  src/test/java/sonia/scm/jenkins/JenkinsRepositoryHookHandlerTest.java
Labels: enhancement

#11 improves resolving and validation of configuration in the event relay
  src/main/java/sonia/scm/jenkins/JenkinsContext.java
  src/main/java/sonia/scm/jenkins/JenkinsEventRelay.java
  src/test/java/sonia/scm/jenkins/JenkinsBranchAndTagEventRelayTest.java
  src/test/java/sonia/scm/jenkins/JenkinsContextTest.java
  src/test/java/sonia/scm/jenkins/JenkinsPullRequestEventRelayTest.java
Labels: bug
